version: 2
jobs:
  buildonly:
    # docker:
    #   - image: circleci/node:latest
    docker:
      - image: salestrip/sfdx-cli      
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: . build/install.sh
      - run:
          name: Create Scratch Org
          command: . build/create-scratch-org.sh
      - run:
          name: Delete Scratch Org
          command: . build/delete-scratch-org.sh
  build:
     # docker:
    #   - image: circleci/node:latest
    docker:
      - image: salestrip/sfdx-cli
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: . build/install.sh
      - run:
          name: Create Scratch Org
          command: . build/create-scratch-org.sh
      - run:
          name: Validate Components & Run Tests
          command: . build/test.sh
      - store_test_results:
          path: test-results
      - run:
          name: Delete Scratch Org
          command: . build/delete-scratch-org.sh
  deploy-prod:
    # docker:
    #   - image: circleci/node:latest
    docker:
      - image: salestrip/sfdx-cli   
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: . build/install.sh
      - run:
          name: Setup Production
          command: . build/setup-prod.sh
      - run:
          name: Deploy to Production
          command: . build/deploy-prod.sh
  deploy-UAT:
    # docker:
    #   - image: circleci/node:latest
    docker:
      - image: salestrip/sfdx-cli   
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: . build/install.sh
      - run:
          name: Setup UAT
          command: . build/setup-uat.sh
      - run:
          name: Deploy to UAT
          command: . build/deploy-uat.sh
workflows:
  version: 2
  validate:
    jobs:
      - deploy-UAT:
          filters:
            branches:
              only:
                - developer
      - deploy-prod:
          filters:
            branches:
              only:
                - master
      - build:
          filters:
            branches:
              only:
                - features
